### ISSUE TITLE
Página de Questionário

### ISSUE THREAD

**Issue by SueldoSales** [CoticEaDIFRN/moodle_theme_proitec#10]

**Comment by SueldoSales** [comment]
- [ ] Nome do usuário sempre aparecendo;
- [ ] Copiar o aside para o NavFlat;
- [ ] Separar o texto das questões;
- [ ] Quando não estiver em questionário ou dentro do curso aparecer somente o nome do usuário;

**Comment by RafaelJovito** [comment]
$('#responseform input').change(function(evt){
    console.log($('[href="#' + $(evt.target).parent().parent().parent().parent().parent().parent().attr('id')+'"]').css('background', 'red') )
})

**Comment by SueldoSales** [comment]
if ($('#questElements').length) { 
    $('#questElements > div > h3').after('<h4 id="textos_title">Textos</h4><div id="textos_links" style="display: flex"></div>');
    $('#questElements .qnbutton:contains(Informação)').appendTo('#textos_links');
    $('#textos_links').after('<h4 id="perguntas_title">Perguntas</h4>');

    $('.aside-calendar').parent().parent().hide() 


    $('#responseform input').change(function (evt){ 
        var paizao = $(evt.target).parent().parent().parent().parent().parent().parent();
        $('[href="#' + paizao.attr('id') +'"]').removeClass('notyetanswered').addClass('answersaved');
    });
    
    // .answersaved {
    //    #39b34a
    //    #fff
    // }
}
